controller_list:
  - name: fake_arm_controller
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5
      - arm_joint_6
      - arm_joint_7
  - name: fake_gripper_controller
    joints:
      - arm_finger_joint
initial:  # Define initial robot poses.
  - group: arm
    pose: home